name: Publish package to PyPi
on: [ push ]
jobs:

  lint:
    name: Lint
    runs-on: python:3.7.4
    steps:
      - uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run lints
        run: flake8 airflow_dbt/ tests/ setup.py

  test:
    name: Test
    runs-on: python:3.7.4
    steps:
      - uses: actions/checkout@master
      - name: Install deps and pytest
        run: pip install --progress-bar off --user . pytest
      - name: Run tests
        run: fpython -m pytest tests/ -sv

  build-n-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install pypa/build
        run: pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish distribution ğŸ“¦ to TEST PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
